apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spot-cluster
  region: ap-south-1

managedNodeGroups:

# `instanceTypes` defaults to [`m5.large`]
- name: spot-1
  spot: true
  ssh:
    publicKeyName: cloudformation_keys

To create cluster with above config file.

eksctl create cluster --config-file=[file-name].yaml
NOTE: Don't forget to delete the cluster.

eksctl delete cluster --config-file=[file-name].yaml