---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    service: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    service: nginx
spec:
  selector:
    name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
    purpose: debug
spec:
  containers:
    - name: almalinux
      image: almalinux
      command: ["sleep","100000"]

