apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: nginx-ns
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
            name: configure-map
