apiVersion: v1
kind: Pod
metadata:
  name: nginx-po
  labels:
    name: nginx-po
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - configMapRef:
            name: configure-map
            key: Name
    
