apiVersion: v1
kind: Pod
metadata:
  name: config-po
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: Name
        valueFrom:
          configMapKeyRef:
            name: configure-map
            key: Name
      