apiVersion: v1
kind: Pod
metadata:
  name: config-po
  labels:
    name: config-po

spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - configMapRef:
          name: configure-map
          key: Name
    
